### ISSUE TITLE
Fix Miami Herald access denied error

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#105]
![miamiherald](https://user-images.githubusercontent.com/9993/175793124-4db69fa3-76a7-4430-b86d-25ed6e85a255.jpg)

**Comment by ChrisArchitect** [comment]
Any idea how to fix these Access Denied issues? They've got the github servers that Actions are running from blocked I'm guessing? Tough one

**Comment by palewire** [comment]
I don't know the answer to this one.

**Comment by palewire** [comment]
I'm going to cut CBC for now
