### ISSUE TITLE
Fix National Post popup

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#107]
![nationalpost](https://user-images.githubusercontent.com/9993/175793146-07d50b55-90c7-41b7-b5fc-659d5d44b0d4.jpg)

**Comment by nikhilnarla** [comment]
Hi @palewire Can you assign this to me? I will soon raise a PR request with the changes. I have made and verified my changes.

**Comment by palewire** [comment]
Go ahead and submit the pull request.

**Comment by nikhilnarla** [comment]
@palewire Done.
