### ISSUE TITLE
Fix PBS News Hour popup

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#109]
![newshour](https://user-images.githubusercontent.com/9993/175793164-5a556cbd-914e-4de1-b50b-2382eb7f090d.jpg)

**Comment by 3swayam** [comment]
@palewire Can you please describe where exactly you need help & what needs to be done ?

**Comment by palewire** [comment]
The HTML element that creates the popup needs to be  identified and then targeted for removal in the JavaScript steps in screenshot.py

**Comment by 3swayam** [comment]
@palewire Can you please assign it to me ?
