### ISSUE TITLE
Fix WRAL popup

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#115]
![wral](https://user-images.githubusercontent.com/9993/175793232-1e86fb64-b2d1-4536-b8d5-7d1d4341dea4.jpg)

**Comment by bhoomikamadhukar** [comment]
Hey @palewire i can look into the issue. Could you help me understand the problem better and what is the output you’re looking for?

**Comment by palewire** [comment]
We need to identify the HTML element that creates the popup and then target it for removal in one of the JavaScript steps in screenshot.py
