### ISSUE TITLE
Fix Hill Times popup

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#137]
![thehilltimes](https://user-images.githubusercontent.com/9993/177635918-1d500baa-79f5-4cb6-be4f-9b38aa17abd3.jpg)

**Comment by AkshMehta** [comment]
When running this command:-
 pipenv run python -m newshomepages.screenshot single latimes

I am getting this error:-
Usage: python -m newshomepages.screenshot [OPTIONS] COMMAND [ARGS]...
Try 'python -m newshomepages.screenshot --help' for help.

Error: No such command 'single'.

**Comment by palewire** [comment]
That bit of documentation is outdated. I can fix it. The command you want to run is:

> pipenv run python -m newshomepages.screenshot shoot latimes

**Comment by AkshMehta** [comment]
> That bit of documentation is outdated. I can fix it. The command you want to run is:
> 
> > pipenv run python -m newshomepages.screenshot shoot latimes

ok thanks
