### ISSUE TITLE
Fix Baltimore Magazine

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#165]
![baltimoremag](https://user-images.githubusercontent.com/9993/178639731-c32db8dd-2810-41d0-846c-ca36d2679b73.jpg)

**Comment by AsaiToshiya** [comment]
Which it be better to include removing script into screenshot.py or add a js file?

**Comment by palewire** [comment]
Either is fine. In cases where the popup appears to be from a third party vendor we can expect on other sites I've started adding them to the global list.

**Comment by AsaiToshiya** [comment]
Thank you for your answer.

I understand.
