### ISSUE TITLE
Add a static chart to the site detail pages with screenshots by date or week

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#198]

**Comment by Mrkojtis** [comment]
👍

Den ons 20 juli 2022 19:07Ben Welsh ***@***.***> skrev:

**Comment by palewire** [comment]
It's live but it's not responsive 
![Screenshot_20220724-215210](https://user-images.githubusercontent.com/9993/180701094-5a88401c-5343-4fc3-9747-fb22a48ed951.png)
