### ISSUE TITLE
Fix Hill Times

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#207]
## Screenshot
![thehilltimes](https://user-images.githubusercontent.com/9993/180602708-521f97c6-50e2-4d85-846d-a3610f15c630.jpg)

A solution is often found by adding JavaScript or CSS via a site-specific include, [as covered in our documentation](https://palewi.re/docs/news-homepages/adding.html#hide-ads-and-popups).

**Comment by parthmarfatia** [comment]
Hi! Could please elaborate more on this issue?

**Comment by palewire** [comment]
The padding between the masthead and the headlines would ideally be cut.

**Comment by parthmarfatia** [comment]
All right! can you assign this issue to me?
