### ISSUE TITLE
Fix Online Khabar

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#214]
## Screenshot
![online_khabar](https://user-images.githubusercontent.com/9993/180712561-843d5bf5-4194-422d-9ff5-9a0b255321d7.jpg)

A solution is often found by adding JavaScript or CSS via a site-specific include, [as covered in our documentation](https://palewi.re/docs/news-homepages/adding.html#hide-ads-and-popups).

**Comment by AAYUSH-droid** [comment]
hey can i work on this issue?

**Comment by AAYUSH-droid** [comment]
hey can you elaborate about what exactly needs to be done?

**Comment by palewire** [comment]
Knock out the popup with JavaScript so it doesn't block the homepage content and ruin the screenshot. See the link in the initial post for directions.
