### ISSUE TITLE
h2 tags in docs have too much bottom padding

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#223]

**Comment by Dun-sin** [comment]
Hi, do you mean this h2 tags?

![image](https://user-images.githubusercontent.com/78784850/183274581-a8728561-40b1-42d5-aa35-789811459fc9.png)
![image](https://user-images.githubusercontent.com/78784850/183274588-3ca0c6fb-dc7e-4a29-addf-e757d76f235b.png)
![image](https://user-images.githubusercontent.com/78784850/183274592-5fa8b5ef-a981-4747-91a0-093de6f5bd83.png)

**Comment by palewire** [comment]
Yes. The issue may need to be addressed by reducing the top margin on the the first p tags

**Comment by Dun-sin** [comment]
> Yes. The issue may need to be addressed by reducing the top margin on the the first p tags

Margin top or margin bottom?
