### ISSUE TITLE
Fix Babylon Bee

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#230]
## Screenshot
![thebabylonbee (1)](https://user-images.githubusercontent.com/9993/183310473-52410167-cc5a-4f2c-8b0c-d1469a4963b6.jpg)

A solution is often found by adding JavaScript or CSS via a site-specific include, [as covered in our documentation](https://palewi.re/docs/news-homepages/adding.html#hide-ads-and-popups).

**Comment by AsaiToshiya** [comment]
If you have not any problem, could you close this issue?

**Comment by palewire** [comment]
Of course. The page on our site shows the problem is clearly fixed. Thanks again. https://palewi.re/docs/news-homepages/sites/thebabylonbee.html
