### ISSUE TITLE
Automate a tweet with performance ranking analysis

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#268]
It could make post a distribution like this. 
![Screenshot from 2022-08-16 15-26-23](https://user-images.githubusercontent.com/9993/184995888-e1d71dd7-b534-41f3-aa14-b539eb19fd38.png)

**Comment by simonw** [comment]
I'd love to see an automated tweet that goes out any time a site makes a significant change to their scores, which at-mentions the site in question

> Ranking update: @nytimes accessibility score just increased from 73 to 81, moving them from 18th to 15th place in the @newshomepages ranking table
