### ISSUE TITLE
Time zone question

### ISSUE THREAD

**Issue by stucka** [palewire/news-homepages#283]
I see the bundle listing includes per-state entries including Florida and Texas, and some states are missing, such as Indiana. Those are explicitly tied to a time zone, but Florida, Indiana and others cover multiple time zones.

Is there a recommended procedure here? E.g., should we default a state to the most common (geography or population) time zone? Should we create separate bundles for the divided areas? Does it matter all that much?

https://www.plansponsor.com/trivial-pursuits-many-states-one-time-zone/

**Comment by stucka** [comment]
Hey, sorry -- I'm not worried about specific time zones in the sites file, but I'm asking about the bundles file:

https://github.com/palewire/news-homepages/blob/main/newshomepages/sources/bundles.csv

Like, florida's listed as America/New_York, and most of the population and land mass is in that time zone, but the western part of the Panhandle is in America/Chicago.

I don't know if anything's actually using the bundles timezone field anyway, but it may be misleading.

**Comment by palewire** [comment]
It's only being used in the tweets right now. Maybe not necessary.
