### ISSUE TITLE
Fix Artha Sarokar

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#297]
## Screenshot
![arthasarokar](https://user-images.githubusercontent.com/9993/192861024-a77b8578-fd69-4030-b4bf-497121170ac4.jpg)

A solution is often found by adding JavaScript or CSS via a site-specific include, [as covered in our documentation](https://palewi.re/docs/news-homepages/adding.html#hide-ads-and-popups).

**Comment by Vinitvh** [comment]
Hi, I would like to work on this.

**Comment by palewire** [comment]
Go ahead
