### ISSUE TITLE
Fix Aspen Daily News

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#298]
## Screenshot
![aspendailynews](https://user-images.githubusercontent.com/9993/192861126-f4f5ae61-c1e2-4e36-927f-5641d919ad68.jpg)

A solution is often found by adding JavaScript or CSS via a site-specific include, [as covered in our documentation](https://palewi.re/docs/news-homepages/adding.html#hide-ads-and-popups).

**Comment by stucka** [comment]
I'm not seeing that popup any more, but I am seeing some stupidly intrusive ads that are likely shared from Blox. Top one appears to be

div#x-reveal-ad

bottom appears to be
div.tnt-ads-container

I'm wary of screwing something up at the moment and I'm tired, but it might be worth seeing if A) those work and B) those should be global. There's a bunch of Blox sites out there.

**Comment by stucka** [comment]
nvm, trying to address with https://github.com/palewire/news-homepages/pull/337

**Comment by stucka** [comment]
Can be closed with merge of https://github.com/palewire/news-homepages/pull/337
