### ISSUE TITLE
Fix Yahoo Finance

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#309]
## Screenshot
![yahoofinance](https://user-images.githubusercontent.com/9993/192862936-f8a18cdc-dd9b-43e0-9061-4b2448ddd088.jpg)

A solution is often found by adding JavaScript or CSS via a site-specific include, [as covered in our documentation](https://palewi.re/docs/news-homepages/adding.html#hide-ads-and-popups).

**Comment by arkbuilder117** [comment]
Hi! Could I work on this?

**Comment by palewire** [comment]
Sure
