### ISSUE TITLE
Fix @htrnews: Popover

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#36]
Gonna pull this one from the routine until we get the popup handled. cc @chrislkeller 

![FOFlE9OVEAAiq0h](https://user-images.githubusercontent.com/9993/158908498-4dec34eb-4fae-44b3-a3d0-e433721e489c.jpeg)

**Comment by chrislkeller** [comment]
Good call... I'm gonna guess that modal is gonna pop up for all of Gannett's Wisco properties as part of an ad network.

Would listening to the DOM for a popup work?
