### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by abidishajia** [palewire/news-homepages#41]
I was testing something, and I found this documentation error. In the [documents](https://palewi.re/docs/news-homepages/adding.html), under **Test the screenshot**, the command to test should be `pipenv run python -m newshomepages.shoot single your-sites-handle` instead of `pipenv run python -m newshomepages.tweet single your-sites-handle`

I tried updating `adding.md` file, but my `blacken-docs` tests are failing. I'm not sure why, but I am debugging. I just wanted to create an issue in case someone else got confused with the command.

**Comment by palewire** [comment]
I made the patch. Thank you.
