### ISSUE TITLE
RSS feeds haven't updated since June 7

### ISSUE THREAD

**Issue by james-tyner** [palewire/news-homepages#482]
It seems that RSS feed generation stopped working on or around June 7. I checked the feeds for several sites and didn't see any homepage links after that date.

Homepage screenshotting and storage seem to be working fine, but those images are no longer accessible via the RSS feed.

**Comment by palewire** [comment]
I will take a look and address. Thank you for flagging it.

**Comment by palewire** [comment]
I pushed a fix. Any better?

**Comment by james-tyner** [comment]
yes! The screenshots are now loading in the feed
