### ISSUE TITLE
Enhancement? Link y-position

### ISSUE THREAD

**Issue by jeremybmerrill** [palewire/news-homepages#487]
Hey Ben: Curious if you'd take a PR to add a column in the links sheet for each link's y-position? 

It'd probably be slightly more surgery than ideal, since [this bit](https://github.com/palewire/news-homepages/blob/main/newshomepages/hyperlinks.py#L60-L70) of link-extraction would probably have to be re-written in JavaScript and executed via Playwright (which I've never done via Playwright but which I have done via Chromedriver and it isn't too weird), since we'd need the page to actually have been rendered (versus the HTML merely parsed by BeautifulSoup).

Edit: The rationale for this would be that users could you y-position to estimate prominence and whether something is "above the fold", one screen down, or ranked in the depths where non-journalists dare not scroll.

**Comment by palewire** [comment]
I'm open to an add. My main ask is that we maintain backwards compatibility with the data we've already collected.

It never got merged, but we did have an idea long these lines submitted a while ago over here: https://github.com/palewire/news-homepages/pull/372

**Comment by jeremybmerrill** [comment]
My proposal would just be to add a new k/v pair in the JSON, e.g. 

```  {
    "text": "Space Flight Without the Rocket Fuel? A Florida-Based Company Is Aiming for the Stars.5 min read",
    "url": "https://www.barrons.com/articles/space-flight-without-the-rocket-fuel-a-florida-based-company-is-aiming-for-the-stars-2867f491?mod=hp_minor_pos32",
    "y": 12345
  }
```

Totally possible I'm underestimating the complexity of this, though!
