### ISSUE TITLE
Take full page shot as well

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#5]

**Comment by palewire** [comment]
This could be a PDF

**Comment by simonw** [comment]
`shot-scraper 0.5` is out with that new PDF command: https://github.com/simonw/shot-scraper/releases/tag/0.5

**Comment by palewire** [comment]
Early experiments with using the pdf output are not goo. 
[nytimes.pdf](https://github.com/palewire/news-homepages/files/8332601/nytimes.pdf)
[latimes.pdf](https://github.com/palewire/news-homepages/files/8332604/latimes.pdf)
