### ISSUE TITLE
Fix @abqbizfirst: Blocked

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#54]
![abqbizfirst](https://user-images.githubusercontent.com/9993/160049950-e55d95f7-6262-4c30-a3f1-2411cd62651c.jpg)

cc @chrislkeller

**Comment by chrislkeller** [comment]
@palewire - I'll ask around and see if our product side folks have any thoughts on why this popped up.

Does it bog anything down now and require removal for the time being?

**Comment by palewire** [comment]
I think I already cut it out.
