### ISSUE TITLE
Fix @newsobserver and @theobserver: Blocked

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#60]
![newsobserver](https://user-images.githubusercontent.com/9993/160245225-a0d279b9-afd4-49ea-90ba-aa7ff2ff19bc.jpg)
![theobserver](https://user-images.githubusercontent.com/9993/160245226-28b8cd43-a323-49ee-9eff-86fa13d6e144.jpg)

**Comment by melodykramer** [comment]
Would you like me to tag someone in from that publication? :)

**Comment by palewire** [comment]
LOL. Why not?

**Comment by AsaiToshiya** [comment]
I think these are User-Agent issue too as #124.

Probably no problem to add those sites.

**Comment by palewire** [comment]
I bet you're right. Let's do it

**Comment by AsaiToshiya** [comment]
I checked the screenshots and they look good.
