### ISSUE TITLE
Le Monde screenshot looks like it has a cookie banner

### ISSUE THREAD

**Issue by detrout** [palewire/news-homepages#95]
Hi, I was looking at the archive of news-homepages at archive.org and spotted that the Le Monde page was blurred and had a cookie popup. I don't know what to do about it, but thought this project might like to know.

![image](https://user-images.githubusercontent.com/975038/170813036-4110da16-e2fc-4c97-9487-08534ce88018.png)

**Comment by detrout** [comment]
I looked at it in firefox's developers tools and it looks like the cookie banner has a div class="gdpr-lmd-standard gdpr-lmd-standard--transparent-deny" node. Deleting that node seems to display the page., though maybe not enough to enabl scroll.

**Comment by palewire** [comment]
Thank you for pointing this out. This type of bug is a great example of why it's important that we ultimately solve #68 and get a universal ad blocker going. For the time being, I've added the class you pointed out to the custom lemonde ad blocker.
